### DISCUSSION TITLE
Adding simulated sensors for currently exporting to/importing from the grid

### DISCUSSION THREAD

**Discussion by rrozema** [hif2k1/battery_sim#136] [Show and tell]
I wanted to show both an energy flow card plus and a power flow card for my simulated battery. For the energy flow card all required sensor are available from the battery_sim device. For the power flow card however, no Power-equivalent exists of the simulated_sensor.energy_consumed and simulated_sensor.energy_produced energy sensors.

Here's what the energy flow card plus diagram looks like for yesterday, september 21st. I can select any period and the numbers will be adjusted to show the totals over that period.
![image](https://github.com/user-attachments/assets/3af10854-686b-47f1-b531-3c74034f38f9)

I also want to use the power flow card to show the current 'live' situation like this:
![image](https://github.com/user-attachments/assets/01b10973-22bd-47cc-956f-cb02585997b3)

However the power flow card requires 2 sensors to populate the left-most circle which are not provided by the battery_sim: power consumed from the grid and power exported to the grid. But, since I do have the power generated by my solar panels, the current discharge and charging rates for the (simulated) battery and the power used by my home I can calculate the missing export and import values.
This is the template I created for the simulated current consumption sensor:
```
{% set bat_out = states('sensor.battery_sim_diy_100k_current_discharging_rate') | float * { 'W' : 1, 'kW' : 1000, 'MW' : 1000000 }[ state_attr('sensor.battery_sim_diy_100k_current_discharging_rate', 'unit_of_measurement')] %}
{% set solar_in = states('sensor.envoy_121831009724_current_power_production') | float * { 'W' : 1, 'kW' : 1000, 'MW' : 1000000 }[ state_attr('sensor.envoy_121831009724_current_power_production', 'unit_of_measurement')] %}
{% set used = states('sensor.envoy_121831009724_current_power_consumption') | float * { 'W' : 1, 'kW' : 1000, 'MW' : 1000000 }[ state_attr('sensor.envoy_121831009724_current_power_consumption', 'unit_of_measurement')] %}
{% set bat_in = states('sensor.battery_sim_diy_100k_current_charging_rate') | float * { 'W' : 1, 'kW' : 1000, 'MW' : 1000000 }[ state_attr('sensor.battery_sim_diy_100k_current_charging_rate', 'unit_of_measurement')] %}

{{ max( 0, (used + bat_in) - (solar_in + bat_out)) }}
```
And this is the template I created for the simulated current production sensor:
```
{% set bat_out = states('sensor.battery_sim_diy_100k_current_discharging_rate') | float * { 'W' : 1, 'kW' : 1000, 'MW' : 1000000 }[ state_attr('sensor.battery_sim_diy_100k_current_discharging_rate', 'unit_of_measurement')] %}
{% set solar_in = states('sensor.envoy_121831009724_current_power_production') | float * { 'W' : 1, 'kW' : 1000, 'MW' : 1000000 }[ state_attr('sensor.envoy_121831009724_current_power_production', 'unit_of_measurement')] %}
{% set used = states('sensor.envoy_121831009724_current_power_consumption') | float * { 'W' : 1, 'kW' : 1000, 'MW' : 1000000 }[ state_attr('sensor.envoy_121831009724_current_power_consumption', 'unit_of_measurement')] %}
{% set bat_in = states('sensor.battery_sim_diy_100k_current_charging_rate') | float * { 'W' : 1, 'kW' : 1000, 'MW' : 1000000 }[ state_attr('sensor.battery_sim_diy_100k_current_charging_rate', 'unit_of_measurement')] %}

{{ max( 0, (solar_in + bat_out) - (used + bat_in)) }}
```

As an example, here are my template sensor settings, the other one is almost identical, except of course for the name and the template:
![image](https://github.com/user-attachments/assets/c9798922-f244-4615-b7a1-16f133450477)

Here's the code to create the both cards shown for the energy:
```
  - type: horizontal-stack
    cards:
      - type: entities
        entities:
          - type: custom:energy-entity-row
            entity: >-
              sensor.battery_sim_diy_100k_simulated_sensor_electricity_meter_energy_consumption_total
            name: Energy imported from Grid
          - type: custom:energy-entity-row
            entity: >-
              sensor.battery_sim_diy_100k_simulated_sensor_electricity_meter_energy_production_total
            name: Energy exported to Grid
          - type: custom:energy-entity-row
            entity: sensor.battery_sim_diy_100k_battery_energy_in
            name: Battery energy charged
          - type: custom:energy-entity-row
            entity: sensor.battery_sim_diy_100k_battery_energy_out
            name: Battery energy discharged
          - type: custom:energy-entity-row
            entity: sensor.battery_sim_diy_100k_extra_money_earned_on_exports
            name: Money earned on exports
          - type: custom:energy-entity-row
            entity: sensor.battery_sim_diy_100k_money_saved_on_imports
            name: Money saved on imports
          - type: custom:energy-entity-row
            entity: sensor.battery_sim_diy_100k_total_energy_saved
            name: Total energy saved
          - type: custom:energy-entity-row
            entity: sensor.battery_sim_diy_100k_total_money_saved
            name: Total money saved
          - type: custom:energy-entity-row
            entity: sensor.battery_sim_diy_100k_battery_cycles
            name: Battery cycles
        title: Selected period
      - type: custom:energy-flow-card-plus
        entities:
          battery:
            entity:
              consumption: sensor.battery_sim_diy_100k_battery_energy_out
              production: sensor.battery_sim_diy_100k_battery_energy_in
            state_of_charge_decimals: 1
            use_metadata: false
            state_of_charge_unit: kWh
          grid:
            entity:
              consumption: >-
                sensor.battery_sim_diy_100k_simulated_sensor_electricity_meter_energy_consumption_total
              production: >-
                sensor.battery_sim_diy_100k_simulated_sensor_electricity_meter_energy_production_total
          solar:
            entity: sensor.envoy_121831009724_lifetime_energy_production
          home: {}
        clickable_entities: true
        display_zero_lines: true
        use_new_flow_rate_model: true
        energy_date_selection: true
        wh_decimals: 0
        kwh_decimals: 3
        min_flow_rate: 1
        max_flow_rate: 6
        max_expected_energy: 2000
        min_expected_energy: 10
        wh_kwh_threshold: 1000
        mwh_decimals: 3
        kwh_mwh_threshold: 999
```

And here's the code i used to create the both 'Live' information cards:
```
  - type: horizontal-stack
    title: Live
    cards:
      - type: entities
        entities:
          - entity: sensor.battery_sim_diy_100k
            name: SOC
          - entity: sensor.battery_sim_diy_100k_battery_mode_now
            name: Battery_mode_now
          - entity: sensor.battery_sim_diy_100k_current_charging_rate
            name: Current charging rate
          - entity: sensor.battery_sim_diy_100k_current_discharging_rate
            name: Current discharging rate
          - entity: >-
              sensor.battery_sim_diy_100k_simulated_sensor_electricity_meter_current_consumption
            name: Import from grid
          - entity: >-
              sensor.battery_sim_diy_100k_simulated_sensor_electricity_meter_current_production
            name: Export to grid
          - entity: select.battery_sim_diy_100k_battery_mode
            name: Battery Mode
          - entity: switch.battery_sim_diy_100k_charge_only
            name: Charge_only
          - entity: switch.battery_sim_diy_100k_discharge_only
            name: Discharge_only
          - entity: switch.battery_sim_diy_100k_force_charge
            name: Force_charge
          - entity: switch.battery_sim_diy_100k_force_discharge
            name: Force_discharge
          - entity: switch.battery_sim_diy_100k_pause_battery
            name: Pause_battery
        show_header_toggle: false
      - type: custom:power-flow-card
        kw_decimals: 3
        watt_threshold: 999
        clickable_entities: true
        entities:
          battery:
            state_of_charge: sensor.battery_sim_diy_100k
            consumption: sensor.battery_sim_diy_100k_current_discharging_rate
            production: sensor.battery_sim_diy_100k_current_charging_rate
          grid:
            consumption: >-
              sensor.battery_sim_diy_100k_simulated_sensor_electricity_meter_current_consumption
            production: >-
              sensor.battery_sim_diy_100k_simulated_sensor_electricity_meter_current_production
          solar: sensor.envoy_121831009724_current_power_production
```
