### DISCUSSION TITLE
Cost tracker

### DISCUSSION THREAD

**Discussion by ObJuanK** [hif2k1/battery_sim#87] [General]
Have installed via HACS on Docker. Battery (tesla) setup and working very well. But I had a question about cost tracking.
I know the documentation saying the following 

> energy_tariff - (optional) the sensor that tracks the energy tarriff - units not supported at present.

When it says units not supported at present, does that talk about kWh, mWh etc? or the whole energy_tariff and cost tracking does not work?

I have been trying for days now to get the costs working but they always remain at 0.

**Comment by Casenl** [comment]
I just tried it this evening, and the costs seem to work for me now. Here is what worked for me.. 
1. Installed the Nordpool add-in to add the current energy prices for my country. (https://github.com/custom-components/nordpool) integration 
2. The Nordpool integration adds a new sensor (entity: nordpool_kwh_nl_eur_3_10_021) that provides the current price, but also with the currency. In my case 0.161 EUR/kWh
4. As the battery sim can only use a number, i need the value of the sensor in step 2, without the "EUR/kWh" part.
5. To do that, i created a new sensor "nordpool_current_price"by adding some lines in the the configuration.yaml
```
sensor:
  - platform: template
    sensors:
      nordpool_current_price:
        friendly_name: "Nordpool Current Price"
        value_template: "{{ state_attr('sensor.nordpool_kwh_nl_eur_3_10_021', 'current_price') }}"

```
7. Restarted Home Assistant 
8. Added the new sensor "nordpool_current_price" in the config for battery_sim

After that, it works for me. Hope this helps.

**Comment by ObJuanK** [comment]
Hey @Casenl, thanks for the explanation. Your implementation got me thinking, I used a local energy company intergration similar to Nordpool, called Amber Electric, they also sell spot pricing in Australia.
I managed to get it going in the way you said, so thank you very much :)

I did have to tweak it a little to get it right for me, as I am on a fixed tariff. I will keep the amber integration and add another battery to compare if switching to a market price model would be better with a battery (i believe it may be, when dialed in)

So based on the information you gave me, I figured the energy_tariff must not be expecting an explicit value set, rather a value from a sensor. 
I created a couple of Number Helpers, with a simple input field, one for import one for export.

![image](https://github.com/hif2k1/battery_sim/assets/70180647/40e563cc-3a17-4256-bddd-cbf69209ee26)


Added them to my battery in the config file like this

```
battery_sim:
  tesla_powerwall:
    name: "battery_sim: Tesla Powerwall"
    import_sensor: sensor.solaredge_imported_energy
    export_sensor: sensor.solaredge_exported_energy
    size_kwh: 13.5
    max_discharge_rate_kw: 5.0
    max_charge_rate_kw: 3.68
    efficiency: 0.9
    energy_tariff: input_number.re_import_price
```

Sadly I reset my battery with a months worth of data in the process and messed up todays actual solar statistics but the fact that "total_money_saved" is no longer 0, I can live with that.


It may be beneficial to others if the documentation was amended to add something along the lines of the above.

Thanks once again!
