### ISSUE TITLE
Feature request: add normal & low energy tariff

### ISSUE THREAD

**Issue by Verguldebarman** [hif2k1/battery_sim#127]
Hi,
Really nice project! I have a suggestion; perhaps you can add normal & low energy in the setup, for (1) consumed/imported, (2) produced/exported and (3) tariff. So something like this:

```
battery_sim:
  sessy_sim:
    name: Sessy Sim 
    import_sensor_tariff_1: sensor.energy_consumed_tariff_1
    import_sensor_tariff_2: sensor.energy_consumed_tariff_2
    export_sensor_tariff_1: sensor.energy_produced_tariff_1
    export_sensor_tariff_2: sensor.energy_produced_tariff_2
    size_kwh: 5.0
    max_discharge_rate_kw: 1.7
    max_charge_rate_kw: 2.2
    efficiency: 0.9
    energy_tariff_1: 0.31
    energy_tariff_2: 0.25
```
