### ISSUE TITLE
Battery not working 

### ISSUE THREAD

**Issue by elRadix** [hif2k1/battery_sim#3]
I added both sensor but nothing is happening,  those are the sensor that used in the energy consumption and both are in kWh. 
Both are created from a template sensor coming from an utility meter as basis. 
I am using a P1 meter to collect the data. 
see below config and screenshot 

 ```
battery_sim:
  tesla_powerwall:
    name: Tesla Powerwall
    import_sensor: sensor.daily_energy
    export_sensor: sensor.daily_injection
    size_kwh: 13.5
    max_discharge_rate_kw: 5.0
    max_charge_rate_kw: 3.68
    efficiency: 0.9
```

```

 utility_meter:
  daily_energy_peak:
    source: sensor.p1_meter_total_power_import_t1
    cycle: daily
  daily_energy_offpeak:
    source: sensor.p1_meter_total_power_import_t2
    cycle: daily
  daily_injection_peak:
    source: sensor.p1_meter_total_power_export_t1
    cycle: daily
  daily_injection_offpeak:
    source: sensor.p1_meter_total_power_export_t2
    cycle: daily
    
sensor:
  - platform: template
    sensors:

      daily_energy:
        friendly_name: Daily Energy
        unique_id: daily_energy
        unit_of_measurement: kWh
        device_class: energy
        value_template: "{{ (states('sensor.daily_energy_offpeak')|float(0) + states('sensor.daily_energy_peak')|float(0)) | round(3)}}"


      daily_injection:
        friendly_name: Daily Injection
        unique_id: daily_injection
        unit_of_measurement: kWh
        device_class: energy
        value_template: "{{ (states('sensor.daily_injection_peak')|float(0) + states('sensor.daily_injection_offpeak')|float(0)) | round(3) }}"

```

![SmartSelect_20211022-131821_Chrome](https://user-images.githubusercontent.com/6258894/138445216-76433291-bfb1-4873-9557-594da76c1af0.jpg)

**Comment by TheGreatHorla** [comment]
![](https://user-images.githubusercontent.com/6258894/138445216-76433291-bfb1-4873-9557-594da76c1af0.jpg)
@elRadix : stupid question but how do you make a card with the attributes visible like in your first post?

**Comment by hif2k1** [comment]
I don't think that's a card, I think it's the entity view. If you go to configuration, entities and find the entity on the list and then click the sliders button in the top right. You can then expand the attributes section at the bottom.

**Comment by elRadix** [comment]
you can this card
```

  type: custom:entity-attributes-card
  title: LG Battery 16KW
  heading_name: List
  heading_state: States
  filter:
    include:
      - key: sensor.lg_chem_prime_16_kw.*
    exclude:
      - key: sensor.lg_chem_prime_16_kw.d*
      - key: sensor.lg_chem_prime_16_kw.f*
      - key: sensor.lg_chem_prime_16_kw.i*
      - key: sensor.lg_chem_prime_16_kw.state*
      - key: sensor.lg_chem_prime_16_kw.u*`
```
![SmartSelect_20211118-103100_Chrome](https://user-images.githubusercontent.com/6258894/142388919-b22aa3e6-a06b-4b9b-acdd-0b048f95d5a2.jpg)


https://github.com/custom-cards/entity-attributes-card
