### ISSUE TITLE
Feature request: support for multiple custom batteries

### ISSUE THREAD

**Issue by vandenberghev** [hif2k1/battery_sim#36]
I'd like simulate multiple custom batteries to determine which one suits my home best.
So I configured multiple `custom:` entries in yaml, but only the last one is used.
Having multiple (unlimited?) custom entries would be very nice to have.

**Comment by hif2k1** [comment]
Can you post your yaml. Did you give them different names?

**Comment by vandenberghev** [comment]
I don't have the original yaml anymore, but I believe I first tried something like:
```yaml
 custom7kWh:
   name: Fake 7kWh Battery
   import_sensor: sensor.xxx
   export_sensor: sensor.yyy
   size_kwh: 7.0
   max_discharge_rate_kw: 3.0
   max_charge_rate_kw: 3.0
   efficiency: 0.9
 custom10kWh:
   name: Fake 10kWh Battery
   import_sensor: sensor.xxx
   export_sensor: sensor.yyy
   size_kwh: 10.0
   max_discharge_rate_kw: 3.0
   max_charge_rate_kw: 3.0
   efficiency: 0.9
```

Etc. But those did not get picked up by HASS at all, so I changed the entries to:

```yaml
 custom:
   name: Fake 7kWh Battery
...
 custom:
   name: Fake 10kWh Battery
   ...
```

And only the last one got picked up by HASS.
